/** Declaration file generated by dts-gen */

declare module 'checkdigit' {
    export const mod10: {
        apply: any
        create: any
        isValid: (a:string) => boolean
    }

    export const mod11: {
        apply: any
        create: any
        isValid: (a:string) => boolean
    }
}

