/** Declaration file generated by dts-gen */

declare module 'checkdigit' {
    export const mod10: {
        apply: (input: string) => string
        create: (input: string) => string
        isValid: (input: string) => boolean
    }

    export const mod11: {
        apply: (input: string) => string
        create: (input: string) => string
        isValid: (input: string) => boolean
    }
}
