name: Build Package

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  Publish:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: build code
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm access token
        run: |
          npm config set @tfso:registry=https://npm.pkg.github.com --userconfig .npmrc
          npm config set //npm.pkg.github.com/:_authToken=${NPM_TOKEN} --userconfig .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TFSO_TOKEN }}

      - name: build project
        run: |
          npm install
          npm run build
